In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import yfinance as yf

In [2]:
# Define period
start = "2018-08-07"
end = "2023-08-07"
period = "1d"

## Hospitality Data Analysis

Name | Symbol
|----|-------|
HST | Host Hotels & Resorts Inc
HLT | Hilton Hotels Corporation
MAR | Marriott International Inc
CHH | Choice Hotels International Inc
H | Hyatt Hotels Corp
<!-- ABNB | Airbnb Inc -->

In [3]:
# symbols = "HST HLT MAR ABNB CHH H"
symbols = "HST HLT MAR CHH H"
stocks_hist = pd.DataFrame({"Stock":[]})

stocks = yf.Tickers(symbols)
for ticker in stocks.tickers:
    df = stocks.tickers[ticker].history(start=start, end=end, period=period)
    df["Stock"] = ticker
    df["% change"] = round(100*(df["Close"] - df["Open"])/df["Open"], 2)
    df = df.reset_index()

    stocks_hist = pd.merge(stocks_hist, df, how="outer")
stocks_hist

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Stock,% change
0,2018-08-07 00:00:00-04:00,18.775547,18.775547,18.531934,18.601538,7584900,0.0,0.0,HST,-0.93
1,2018-08-08 00:00:00-04:00,18.671144,18.923458,17.809801,17.879404,12959400,0.0,0.0,HST,-4.24
2,2018-08-09 00:00:00-04:00,17.862002,17.966407,17.792399,17.827200,11420100,0.0,0.0,HST,-0.19
3,2018-08-10 00:00:00-04:00,17.757601,17.818504,17.522689,17.635796,8288300,0.0,0.0,HST,-0.69
4,2018-08-13 00:00:00-04:00,17.635794,17.740198,17.383480,17.487886,6328700,0.0,0.0,HST,-0.84
...,...,...,...,...,...,...,...,...,...,...
6280,2023-07-31 00:00:00-04:00,125.790001,127.800003,125.790001,126.349998,782800,0.0,0.0,H,0.45
6281,2023-08-01 00:00:00-04:00,125.750000,126.349998,123.459999,125.029999,754000,0.0,0.0,H,-0.57
6282,2023-08-02 00:00:00-04:00,123.550003,124.720001,122.300003,122.339996,1049900,0.0,0.0,H,-0.98
6283,2023-08-03 00:00:00-04:00,116.000000,116.000000,110.599998,111.989998,2209700,0.0,0.0,H,-3.46
6284,2023-08-04 00:00:00-04:00,112.660004,115.410004,111.830002,112.230003,914800,0.0,0.0,H,-0.38

In [4]:
# Export Stock Data to CSV
stocks_hist.to_csv("data/hosp.csv", index=False)